### PR TITLE
Update to new URL parser

### PR DESCRIPTION
**Pull request by cyberwombat**
Updated for newUrlParser. Removed test with no database names as they no longer apply. Also removed multi database test as Mongo now rejects multiple url to same host and hard to test with different hosts. This is a breaking change so version should be updated accordingly.

### CODE REVIEW

**Comment by cyberwombat** [comment]
Changed how options were handled for Travis

**Comment by cyberwombat** [comment]
Hmmm. No idea what's wrong with Travis. Timed out?

**Comment by lependu** [comment]
Sorry, I havent realized you working on this too. I created a PR with a different approach, because it would be hard to explain it with words.

**Comment by cyberwombat** [comment]
@lependu no worries - as long as it gets done all ways are good. Re multi url testing  - this could be done using in memory mongo but don't know it's worth it.

**Comment by mcollina** [comment]
How would you like to proceed? Can you two reconvene on which PR is preferred?

**Comment by cyberwombat** [comment]
Flip a coin :)

**Comment by cyberwombat** [comment]
@mcollina Let's use @lependu PR. I was a bit more harsh with the removal of no database tests in the assumption that one needed to always pass a database name. But i guess this can be added at runtime.

**Pull request closed without merging**
