### PR TITLE
Update to fastify@4

### PR DESCRIPTION
**Pull request by Eomm**

### CODE REVIEW

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by Fdawgs — CHANGES_REQUESTED** [review]
Plugin "name" and "fastify" values needs updating as well 😊

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Eomm** [comment]
> Plugin "name" and "fastify" values needs updating as well 😊

Assuming you are referring to:

```
module.exports = fp(fastifyMongodb, {
  fastify: '>=1.0.0',
  name: 'fastify-mongodb'
})
```

I read in some other PRs that it was ok to keep the the general value if it match the v4

Regarding the name: is it ok the new package name right? `@fastify/mongodb`

**Comment by mcollina** [comment]
yes exactly

**Comment by Fdawgs** [comment]
Yeah, cheers @Eomm

**Pull request merged**
