### PR TITLE
chore: move mongodb to devDeps and add it to peerDeps

### PR DESCRIPTION
**Pull request by rtritto**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by gurgunday — CHANGES_REQUESTED** [review]
Thanks for the PR!

If I understand peerDeps correctly, this risks not installing mongoDB if a user installs packages using npm ci --omit=dev

**Comment by rtritto** [comment]
The default value of _omit_ option is _dev_.
From _npm_ version >= 7 (Node >= v16) peer dependencies are autoinstalled: [source](https://github.com/npm/rfcs/blob/main/implemented/0025-install-peer-deps.md).

**Comment by mcollina** [comment]
Unfortunately the minimum supported version of this module is Node v14.

**Comment by mcollina** [comment]
Generically we prefer to stay away from peerdependencies because they create more problems than what they are worth.

**Comment by rtritto** [comment]
> Unfortunately the minimum supported version of this module is Node v14.

For `mongodb` v6 the minimum supported Node.js version is v16.20.1 ([source](https://github.com/mongodb/node-mongodb-native/releases/tag/v6.0.0)).

**Comment by gurgunday** [comment]
Oof, that's correct, good catch

A PR that downgrades it is welcome

**Comment by mcollina** [comment]
I would really prefer avoiding peerDependencies anyway. They are just a source of headaches for maintainers.

**Comment by rtritto** [comment]
Node v14 isn't mantained, when it will be removed?

**Comment by gurgunday** [comment]
When Fastify v5 is released (probably by the end of this year)

**Comment by climba03003** [comment]
I am closing the PR because we avoid using peerDependencies in any case.
So, it is not going to merge in anytime.

**Pull request closed without merging**
