### PR TITLE
added collection factory

### PR DESCRIPTION
**Pull request by helloIAmPau**
Hello all,
I've added the ability for a developer to define _initializer functions_ to collections using the main options object. 

In my use case, I need to ensure the definition of some indexes on some collection.
Thanks to my patch I can create them easily using the following `options` object
```javascript
app.register(mongo, {
    url: process.env.MONGO,
    collections: {
      users: function(collection) {
        return collection.createIndex({
          mail: 1
        }, {
          unique: true
        });
      }
    }
  });
```

The initialization functions are triggered only if the database name is defined (either via mongo url or explicit property).

Bye

### CODE REVIEW

**Comment by mcollina** [comment]
Can you remove the package-lock file and document this new feature in the README?

**Comment by helloIAmPau** [comment]
Sure.

I'm glad you like the feature.

**Comment by helloIAmPau** [comment]
@delvedor my idea here is to provide an agile way to initialize the collections alongside the db initialization. This seems to not collide with the concept of separation of concerns IMHO.

By the way, I'm ok with moving this code in another plugin more _collection oriented_ too (that was my initial idea).

**Comment by delvedor** [comment]
> This seems to not collide with the concept of separation of concerns IMHO.

Yes, but you are adding logic that is not strictly needed for this plugin to work. The scope of this plugin is to give you a mongodb working connection.
Everything else are nice utilities, but I fear that adding all of them here will make this plugin hard to maintain.

**Comment by helloIAmPau** [comment]
@delvedor I see. By the way, I can write the wrapper plugin if you decide to reject this patch :+1:

**Comment by mcollina** [comment]
Closing for no activity.

**Pull request closed without merging**
