### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by cemremengu**
Add win build, remove node 9

### CODE REVIEW

**Comment by mcollina** [comment]
CI is failing

**Comment by cemremengu** [comment]
I am not really sure why this fails though

**Comment by mcollina** [comment]
no mongo it seems

Il giorno dom 21 ott 2018 alle 12:10 Cemre Mengu <notifications@github.com>
ha scritto:

**Comment by cemremengu** [comment]
According to [this](https://travis-ci.community/t/mongodb-service-does-not-start-on-windows/445), we will need a more complicated setup script to run `mongodb` on travis windows at the moment.

Should we proceed or wait until it is sorted out?

**Comment by mcollina** [comment]
Let's just wait this.

**Comment by mcollina** [comment]
Let's just reassess later. I don't think it's worth the effort.

**Comment by mcollina** [comment]
Let's just reassess later. I don't think it's worth the effort.

**Comment by cemremengu** [comment]
Closing this for later, lets not keep it lingering around

**Pull request closed without merging**
