### PR TITLE
use new url parser

### PR DESCRIPTION
**Pull request by StarpTech**
This will fix https://github.com/fastify/fastify-mongodb/issues/51

### CODE REVIEW

**Comment by mcollina** [comment]
CI is failing.

**Comment by StarpTech** [comment]
Yes, I already investigate

**Comment by StarpTech** [comment]
@mcollina that change is not so easy as expected. I run into some hard issues like 

```
MongoError: no primary found in replicaset
```

I have no time to investigate further but I will create a PR when I can reproduce in my current project. In the meantime, the user can pass the option to the mongo client.

**Comment by wrbl606** [comment]
Hey @StarpTech, any updates on this issue?
The proposed
> In the meantime, the user can pass the option to the mongo client.

solution is not ideal since it disables automatic close of client connection.

**Comment by cyberwombat** [comment]
I take that back. Would be a mess to try to parse and add the name to multi mongo url.

**Pull request closed without merging**
