### PR TITLE
Move @tpyes/mongodb to dependemcies

### PR DESCRIPTION
**Pull request by fuafa**
`@types/mongodb` should go to `dependencies`, since it is used in the `index.d.ts`. Now all types from mongo are `any`
image

### CODE REVIEW

**Comment by cemremengu** [comment]
@mcollina what's our general policy on this? Do we move in types or have people install them separately as `devDependencies` ?

**Comment by evanshortiss** [comment]
Since we include MongoDB with this module I think this makes sense. It's definitely not ideal for install size reasons for vanilla JS users though I wonder what the broader community take on this might be.

**Comment by fuafa** [comment]
Found an explanation why library author should place `@types` in `dependencies`, https://github.com/microsoft/types-publisher/issues/81
Btw, vanilla JS users would still benefit from the autocompletion, when they have the type information.

**Comment by mcollina** [comment]
@Ethan-Arrowood what do you think in this case?

**Comment by Ethan-Arrowood** [comment]
This is a great example of why we ship our own types! Because mongo doesn't ship its own types **we do need to include @types/mongo in our dependencies**. If mongo shipped its own types then we wouldn't as they would have been automatically included through the single `mongo` dependency.

**Pull request closed without merging**
