### PR TITLE
feat: re-export ObjectId from mongodb

### PR DESCRIPTION
**Pull request by iShibi**
Closes: #138

This PR re-exports the `ObjectId` from `mongodb`. `ObjectId('id')` should work for JS users but TS users will have to create an instance to do the same i.e. `new ObjectId('id')`. The compiler will complain if you don't use the `new` keyword even tho it works at runtime if you ignore the error.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by climba03003 — CHANGES_REQUESTED** [review]
Can you add an unit for the exportation.

**Review by Eomm — COMMENTED** [review]
Could you update the documentation as well?

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you please add unit tests for both the js and ts changes?

**Review by climba03003 — APPROVED** [review]
LGTM.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
